
github:
  id: milkcoke
  email: mbh023@gmail.com
  owner: milkcoke
  repo: toolbox-gui
  release_id: 1

aws:
  region: ap-northeast-2

  s3:
    region: ${aws.region}
    bucket_name: toolbox-app-info

  ses:
    email: mbh023@gmail.com
